FROM java:8-alpine
MAINTAINER Your Name <you@example.com>

ADD target/inflacao-pedestal-service-0.0.1-SNAPSHOT-standalone.jar /inflacao-pedestal-service/app.jar

EXPOSE 8080

CMD ["java", "-jar", "/inflacao-pedestal-service/app.jar"]
